git:
  depth: false

language: java

env:
  global:
    - LC_ALL=en_US.UTF-8
    - JAVA_JDK=https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-jdk8.0.232-linux_x64.tar.gz

jobs:
  include:
    - name: "OpenJDK8"
      env:
        - secure: AQuPO2Lo3bkxMe969ajJ4rSfBUHs5//WqaRfWTK9E6cD/mHSE5hREg9KPVSzYxaReJFJz/Vd+ietAEGtWx47BMHDPYJwqILpuia1uiVZv5TA8vrhSzW9NXar9IVWDGMxZH4sbM6l0xPY/8V++aZCEQPc/TYf8Sog5puTjR5yDbPVlMenP4Y5d71YvUl+nyag6sjfdK8bQ0xWmGKuZAJbXk9k1bAeLFXuwHLZ2jwAIdVVeSBOubG371qE5shURAhgqQ7p/YXz14Z6tuGKzomfsjtNzgunr8CrXUovaNAn8TWntVhtfnlnH3U7bYJE/bFDYCkOzDqUBfbuN5vgBtTJzk6Md9HgwAK5i44riLo7YoYxwATD4PXLeT3HUHU0ly19+n1OkwbguDe0FZ9vKT0enSAsOP9EOYBwQhdWLfAd6O3JcDzZy/E2CPDeX0iK6bHF3Lq83vDWy0AZB9X98GI7HJIzy4r+NVFCFCQiXd++Oi4ePDq/LwFFIq/2xCkTLNWkikGmf3aa8ETm8QG+mqfbZe6sEPP6ZL8634ZiHIHSiYkpSep+39hjHz74IV0PnQNuRMquUEeXZwqXt/GVLSAoEHEgfwda7uoQrGpqbgIOKKpbJl0HcF/6fU7er68otWpQFd7e+QVXd7cfkTQA95dH9n7AsKsqTScZejFMdxjVMSM=
    - name: "OpenJDK11"
      env:
        - JAVA_JDK=https://cdn.azul.com/zulu/bin/zulu11.35.15-ca-jdk11.0.5-linux_x64.tar.gz
    - name: "BndNext"
      env: ALLOW_FAILURE=true
      script:
        - "./mvnw --no-transfer-progress --settings settings.xml clean install -Pbnd-next"
  allow_failures:
    - env: ALLOW_FAILURE=true

before_install:
  - "unset _JAVA_OPTIONS"
  - "curl -O -L --retry 3 https://github.com/sormuras/bach/raw/master/install-jdk.sh"

install:
  - "source install-jdk.sh --url $JAVA_JDK"

before_script:
  - "./mvnw --version --settings settings.xml"

script:
  - "./mvnw --no-transfer-progress --settings settings.xml clean install"

after_success:
  - "if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a ${OSSRH_USERNAME:=X} != X ]; then ./mvnw --settings settings.xml deploy; fi"
